name: gb_marketing
description: A furture ecommerce application

publish_to: 'none' 

version: 1.7.6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  get_storage: ^2.0.3
  http: ^0.13.4
  google_fonts: ^2.1.0
  sizer: ^2.0.15
  cached_network_image: ^3.0.0
  animations: ^2.0.2
  badges: ^2.0.1
  flutter_star_rating: ^0.0.3
  flutter_swiper: ^1.1.6
  pinput: ^1.2.2
  fluttertoast:
  upgrader: ^3.13.0
  share: ^2.0.4
  razorpay_flutter: ^1.2.7
  url_launcher: ^6.0.15
  hexcolor: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
 
flutter:

  uses-material-design: true

  assets:
    - assets/
